### ISSUE TITLE
Help on linux

### ISSUE THREAD

**Issue by DrCod3r** [rodrigogs/ilsap#1]
/usr/local/lib/node_modules/ilsap/index.js:2
const { URL } = require('url');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ilsap/bin/ilsap:12:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by rodrigogs** [comment]
Update your node version. Note that this ilsap only works on node 7.6 or higer.

**Comment by rodrigogs** [comment]
Closing due to inactivity.
