### ISSUE TITLE
Error on launching ilsap

### ISSUE THREAD

**Issue by defrox** [rodrigogs/ilsap#10]
➜  ~ ilsap
/usr/local/lib/node_modules/ilsap/index.js:2
const { URL } = require('url');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ilsap/bin/ilsap:14:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by rodrigogs** [comment]
Same as https://github.com/rodrigogs/ilsap/issues/9
