### ISSUE TITLE
Version 1.2.0 Exception 

### ISSUE THREAD

**Issue by seanhuni** [rodrigogs/ilsap#6]
`module.js:471
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/sean/idea.licence/ilsap/bin/ilsap:4:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
`

**Comment by guidodobboletta** [comment]
You need to give a lot more information about your environment when creating an issue.

**Comment by rodrigogs** [comment]
I'm closing this issue due to op's inactivity.
