### ISSUE TITLE
Ubuntu 17.10 error

### ISSUE THREAD

**Issue by danjee** [rodrigogs/ilsap#7]
I have the following error:

comand: ilsap -s http://xidea.online

output:
/usr/local/lib/node_modules/ilsap/index.js:25
  const server = http.createServer(async (req, res) => {
                                         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ilsap/bin/ilsap:13:1)

environment
Linux asus-rog 4.13.0-25-generic #29-Ubuntu SMP Mon Jan 8 21:14:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

npm version 3.5.2
nodejs version v6.11.4

Any ideas
Thanks

**Comment by danjee** [comment]
ilsap version is 1.2.0

**Comment by danjee** [comment]
Oh, I see the warning. I need a bigger nodejs version

**Comment by guidodobboletta** [comment]
Exactly, you need at least `Node 7.6`.
