### ISSUE TITLE
Error http.createServer on win10

### ISSUE THREAD

**Issue by mr0bles** [rodrigogs/ilsap#9]
C:\Users\USER\AppData\Roaming\npm\node_modules\ilsap\index.js:36
  const server = http.createServer(async (req, res) => {
                                         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\ilsap\bin\ilsap:14:1)

**Comment by belicslavko** [comment]
I have the same problem, check "node 7.6 > required"

**Comment by rodrigogs** [comment]
Same as https://github.com/rodrigogs/ilsap/issues/1
